-- noinspection SqlResolve
-- Таблица событий пользователей для ленты активности

CREATE TABLE IF NOT EXISTS events (
    event_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER      NOT NULL,
    event_type       VARCHAR(20)  NOT NULL,
    operation        VARCHAR(20)  NOT NULL,
    entity_id        INTEGER      NOT NULL,
    event_timestamp  BIGINT       NOT NULL,
    CONSTRAINT fk_events_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT chk_event_type CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),
    CONSTRAINT chk_event_operation CHECK (operation IN ('REMOVE', 'ADD', 'UPDATE'))
);

CREATE INDEX IF NOT EXISTS idx_events_user ON events (user_id);
