-- Базовое создание схемы Filmorate.
-- Здесь задаём только структуру, без наполнения справочников.

-- Таблица пользователей с уникальными логином и email.
CREATE TABLE IF NOT EXISTS users (
    user_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL UNIQUE,                 -- e-mail обязателен и должен быть уникальным
    login        VARCHAR(255) NOT NULL UNIQUE,                 -- логин также уникален, чтобы избежать дублей
    user_name    VARCHAR(255),                                 -- отображаемое имя, может быть пустым
    birthday     DATE,                                         -- дата рождения без времени
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()        -- технический штамп для отладки
);

-- Справочник возрастных рейтингов MPA.
CREATE TABLE IF NOT EXISTS mpa (
    mpa_id   SMALLINT PRIMARY KEY,                             -- идентификатор задаётся вручную в сидере
    mpa_name VARCHAR(50) NOT NULL UNIQUE                       -- краткое обозначение рейтинга
);

-- Справочник жанров.
CREATE TABLE IF NOT EXISTS genres (
    genre_id   SMALLINT PRIMARY KEY,                           -- идентификатор жанра, задаётся вручную
    genre_name VARCHAR(255) NOT NULL UNIQUE                    -- человекочитаемое название жанра
);

-- Основная таблица фильмов.
CREATE TABLE IF NOT EXISTS films (
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    VARCHAR(255) NOT NULL,                        -- название фильма
    description  VARCHAR(200),                                 -- краткое описание, ограничено 200 символами
    release_date DATE,                                         -- дата релиза фильма
    duration     INTEGER,                                      -- продолжительность в минутах
    mpa_id       SMALLINT REFERENCES mpa(mpa_id),              -- ссылка на возрастной рейтинг
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Связь фильмов и жанров (многие-ко-многим).
CREATE TABLE IF NOT EXISTS film_genre (
    film_id  INTEGER NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    genre_id SMALLINT NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)                            -- запрещаем дубликаты жанров для одного фильма
);

-- Справочник режиссёров.
CREATE TABLE IF NOT EXISTS directors (
    director_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name VARCHAR(255) NOT NULL                         -- имя режиссёра
);

-- Связь фильмов и режиссёров (многие-ко-многим).
CREATE TABLE IF NOT EXISTS film_director (
    film_id     INTEGER NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    director_id BIGINT NOT NULL REFERENCES directors(director_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)                          -- один режиссёр не может дублироваться в фильме
);

-- Лайки фильмов от пользователей.
CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),          -- когда лайк поставили
    PRIMARY KEY (film_id, user_id)                              -- один пользователь может лайкнуть фильм только раз
);

-- Дружба между пользователями (двусторонняя модель).
CREATE TABLE IF NOT EXISTS friendships (
    user_id   INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    friend_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),          -- фиксируем дату установления дружбы
    PRIMARY KEY (user_id, friend_id),
    CHECK (user_id <> friend_id)                                -- пользователь не может дружить сам с собой
);

-- Отзывы пользователей о фильмах.
CREATE TABLE IF NOT EXISTS reviews (
    review_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     TEXT NOT NULL,                                  -- текст отзыва
    is_positive BOOLEAN NOT NULL,                               -- признак «положительный / отрицательный»
    user_id     INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    film_id     INTEGER NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    useful      INTEGER NOT NULL DEFAULT 0,                     -- агрегированное значение полезности
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),         -- когда отзыв создан
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Оценки отзывов (лайки/дизлайки), нужны для расчёта useful.
CREATE TABLE IF NOT EXISTS review_ratings (
    review_id   INTEGER NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id     INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    is_positive BOOLEAN NOT NULL,                               -- true = like, false = dislike
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (review_id, user_id)                            -- один голос на пользователя
);

-- События для ленты активности.
CREATE TABLE IF NOT EXISTS events (
    event_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_timestamp BIGINT NOT NULL,                            -- метка времени в миллисекундах
    user_id         INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    event_type      VARCHAR(20) NOT NULL,                       -- LIKE/REVIEW/FRIEND
    operation       VARCHAR(20) NOT NULL,                       -- ADD/REMOVE/UPDATE
    entity_id       INTEGER NOT NULL,                           -- id сущности, к которой относится событие
    CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),         -- защита от опечаток
    CHECK (operation IN ('ADD', 'REMOVE', 'UPDATE'))
);

-- Индексы для ускорения выборок, используемых в репозиториях.
CREATE INDEX IF NOT EXISTS idx_films_mpa ON films(mpa_id);
CREATE INDEX IF NOT EXISTS idx_likes_user ON likes(user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_friend ON friendships(friend_id);
CREATE INDEX IF NOT EXISTS idx_reviews_film ON reviews(film_id);
CREATE INDEX IF NOT EXISTS idx_review_ratings_user ON review_ratings(user_id);
CREATE INDEX IF NOT EXISTS idx_events_user ON events(user_id);
