-- noinspection SqlResolve
-- Добавление таблицы отзывов и таблицы оценок отзывов

-- Таблица отзывов
CREATE TABLE IF NOT EXISTS reviews (
                                       review_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       content     TEXT    NOT NULL,
                                       is_positive BOOLEAN NOT NULL,
                                       user_id     INTEGER NOT NULL,
                                       film_id     INTEGER NOT NULL,
                                       useful      INTEGER DEFAULT 0,
                                       FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
                                       FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE
);

-- Таблица оценок отзывов (лайки/дизлайки на отзывы)
CREATE TABLE IF NOT EXISTS review_rating (
                                             review_id  INTEGER NOT NULL,
                                             user_id    INTEGER NOT NULL,
                                             is_useful  BOOLEAN NOT NULL,
                                             PRIMARY KEY (review_id, user_id),
                                             FOREIGN KEY (review_id) REFERENCES reviews (review_id) ON DELETE CASCADE,
                                             FOREIGN KEY (user_id)   REFERENCES users (user_id)   ON DELETE CASCADE
);
